services:
  - type: web
    name: app
    env: docker
    repo: https://github.com/calderonic/deploy-java
    branch: master
    dockerfilePath: Back/Dockerfile
    port: 8080
    envVars:
      - key: DB_URL
        value: jdbc:mysql://db:3306/childcare?createDatabaseIfNotExist=true&serverTimezone=UTC
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 12345
    startCommand: "docker-compose -f Back/docker-compose.yml up app"

  - type: private
    name: db
    env: docker
    image: mysql:8.0.23
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: 12345
      - key: MYSQL_PASSWORD
        value: 12345
      - key: MYSQL_DATABASE
        value: childcare
    startCommand: "docker-compose -f Back/docker-compose.yml up db"
    volumes:
      - name: data-mysql
        path: /var/lib/mysql
